CREATE TABLE tableName 
(
    movie	VARCHAR(512),
    released	INT
);

INSERT INTO tableName (movie, released) VALUES ('El Padrino', '1');
INSERT INTO tableName (movie, released) VALUES ('Los Siete Samurais', '2');
INSERT INTO tableName (movie, released) VALUES ('El Padrino II', '3');
INSERT INTO tableName (movie, released) VALUES ('Pulp Fiction', '4');
INSERT INTO tableName (movie, released) VALUES ('Lawrence de Arabia', '5');
INSERT INTO tableName (movie, released) VALUES ('La Lista de Schindler', '6');
INSERT INTO tableName (movie, released) VALUES ('Tempos Modernos', '7');
INSERT INTO tableName (movie, released) VALUES ('The Hunt', '8');
INSERT INTO tableName (movie, released) VALUES ('El Crepúsculo de los Dioses', '9');
INSERT INTO tableName (movie, released) VALUES ('M, El Vampiro de Düsseldorf', '10');
INSERT INTO tableName (movie, released) VALUES ('Uno de los Nuestros', '11');
INSERT INTO tableName (movie, released) VALUES ('El Viaje de Chihiro', '12');
INSERT INTO tableName (movie, released) VALUES ('Luces de la Ciudad', '13');
INSERT INTO tableName (movie, released) VALUES ('El Bueno, el Feo y el Malo', '14');
INSERT INTO tableName (movie, released) VALUES ('Stalker', '15');
INSERT INTO tableName (movie, released) VALUES ('Dr. Strangelove', '16');
INSERT INTO tableName (movie, released) VALUES ('Apocalypse Now', '17');
INSERT INTO tableName (movie, released) VALUES ('Casablanca', '18');
INSERT INTO tableName (movie, released) VALUES ('Cadena Perpetua', '19');
INSERT INTO tableName (movie, released) VALUES ('La Ventana Indiscreta', '20');
INSERT INTO tableName (movie, released) VALUES ('Ciudadano Kane', '21');
INSERT INTO tableName (movie, released) VALUES ('Ladrón de Bicicletas', '22');
INSERT INTO tableName (movie, released) VALUES ('Vértigo', '23');
INSERT INTO tableName (movie, released) VALUES ('Taxi Driver', '24');
INSERT INTO tableName (movie, released) VALUES ('Rashomon', '25');
INSERT INTO tableName (movie, released) VALUES ('Psicosis', '26');
INSERT INTO tableName (movie, released) VALUES ('Atrapados sin Salida', '27');
INSERT INTO tableName (movie, released) VALUES ('El Tercer Hombre', '28');
INSERT INTO tableName (movie, released) VALUES ('Hasta que Llegó su Hora', '29');
INSERT INTO tableName (movie, released) VALUES ('Star Wars - Episodio V - El Imperio Contrataca', '30');
INSERT INTO tableName (movie, released) VALUES ('La Ley del Silencio', '31');
INSERT INTO tableName (movie, released) VALUES ('Vivir', '32');
INSERT INTO tableName (movie, released) VALUES ('Yojimbo', '33');
INSERT INTO tableName (movie, released) VALUES ('Star Wars - Episodio IV - Una Nueva Esperanza', '34');
INSERT INTO tableName (movie, released) VALUES ('Los 400 Golpes', '35');
INSERT INTO tableName (movie, released) VALUES ('Cantando Bajo la Lluva', '36');
INSERT INTO tableName (movie, released) VALUES ('En Busca del Arca Perdida', '37');
INSERT INTO tableName (movie, released) VALUES ('El Caballero Oscuro', '38');
INSERT INTO tableName (movie, released) VALUES ('Chinatown', '39');
INSERT INTO tableName (movie, released) VALUES ('Metrópolis', '40');
INSERT INTO tableName (movie, released) VALUES ('Fanny y Alexander', '41');
INSERT INTO tableName (movie, released) VALUES ('Senderos de Gloria', '42');
INSERT INTO tableName (movie, released) VALUES ('Perdicióm', '43');
INSERT INTO tableName (movie, released) VALUES ('La Noche del Cazador', '44');
INSERT INTO tableName (movie, released) VALUES ('Amanecer', '45');
INSERT INTO tableName (movie, released) VALUES ('2001: Una Odisea del Espacio', '46');
INSERT INTO tableName (movie, released) VALUES ('Que Bello es Vivir', '47');
INSERT INTO tableName (movie, released) VALUES ('Toro Salvaje', '48');
INSERT INTO tableName (movie, released) VALUES ('Eva al Desnudo', '49');
INSERT INTO tableName (movie, released) VALUES ('Con la Muerte en los Talones', '50');
INSERT INTO tableName (movie, released) VALUES ('El Salario del Miedo', '51');
INSERT INTO tableName (movie, released) VALUES ('Cuentos de Tokio', '52');
INSERT INTO tableName (movie, released) VALUES ('El Silencio de los Inocentes', '53');
INSERT INTO tableName (movie, released) VALUES ('Nader y Simin, Una Separación', '54');
INSERT INTO tableName (movie, released) VALUES ('El Tersoro de Sierra Madre', '55');
INSERT INTO tableName (movie, released) VALUES ('Ran', '56');
INSERT INTO tableName (movie, released) VALUES ('El Señor de los Anillos: La Comunidad del Anillo', '57');
INSERT INTO tableName (movie, released) VALUES ('Persona ', '58');
INSERT INTO tableName (movie, released) VALUES ('El Señor de los Anillos: Las dos Torres', '59');
INSERT INTO tableName (movie, released) VALUES ('El Séptimo Sello', '60');
INSERT INTO tableName (movie, released) VALUES ('La Tumba de las Luciérnagas', '61');
INSERT INTO tableName (movie, released) VALUES ('Fellini 8 1/2', '62');
INSERT INTO tableName (movie, released) VALUES ('Sed de Mal', '63');
INSERT INTO tableName (movie, released) VALUES ('Alien, el Octavo Pasajero', '64');
INSERT INTO tableName (movie, released) VALUES ('La Batalla de Argel', '65');
INSERT INTO tableName (movie, released) VALUES ('El Maquinista de la General', '66');
INSERT INTO tableName (movie, released) VALUES ('La Pasión de Juana de Arco', '67');
INSERT INTO tableName (movie, released) VALUES ('Toy Story', '68');
INSERT INTO tableName (movie, released) VALUES ('El Puente Sobre el Río Kwai', '69');
INSERT INTO tableName (movie, released) VALUES ('Annie Hall', '70');
INSERT INTO tableName (movie, released) VALUES ('El Señor de los Anillos: El Retorno del Rey', '71');
INSERT INTO tableName (movie, released) VALUES ('Toy Story 3', '72');
INSERT INTO tableName (movie, released) VALUES ('La Quimera del Oro', '73');
INSERT INTO tableName (movie, released) VALUES ('El Gran Dictador', '74');
INSERT INTO tableName (movie, released) VALUES ('Ciudad de Dios', '75');
INSERT INTO tableName (movie, released) VALUES ('Fresas Salvajes', '76');
INSERT INTO tableName (movie, released) VALUES ('El Apartamento', '77');
INSERT INTO tableName (movie, released) VALUES ('Andrei Rublev', '78');
INSERT INTO tableName (movie, released) VALUES ('Rescatando al Soldado Ryan', '79');
INSERT INTO tableName (movie, released) VALUES ('Volver al Futuro', '80');
INSERT INTO tableName (movie, released) VALUES ('El Laberinto del Fauno', '81');
INSERT INTO tableName (movie, released) VALUES ('Con Faldas y a lo Loco', '82');
INSERT INTO tableName (movie, released) VALUES ('El Mago de Oz', '83');
INSERT INTO tableName (movie, released) VALUES ('La Vida de los Otros', '84');
INSERT INTO tableName (movie, released) VALUES ('Amadeus', '85');
INSERT INTO tableName (movie, released) VALUES ('Tres Colores: Rojo', '86');
INSERT INTO tableName (movie, released) VALUES ('Eterno Resplandor', '87');
INSERT INTO tableName (movie, released) VALUES ('Sucedió una Noche', '88');
INSERT INTO tableName (movie, released) VALUES ('Aliens: El Regreso', '89');
INSERT INTO tableName (movie, released) VALUES ('Los Caballeros de la Mesa Cuadrada', '90');
INSERT INTO tableName (movie, released) VALUES ('Wall-E', '91');
INSERT INTO tableName (movie, released) VALUES ('Tiburón', '92');
INSERT INTO tableName (movie, released) VALUES ('La Dolce Vita', '93');
INSERT INTO tableName (movie, released) VALUES ('La Gran Ilusión', '94');
INSERT INTO tableName (movie, released) VALUES ('El Submarino', '95');
INSERT INTO tableName (movie, released) VALUES ('L.A. Confidential', '96');
INSERT INTO tableName (movie, released) VALUES ('El Chico', '97');
INSERT INTO tableName (movie, released) VALUES ('Cinema Paradiso', '98');
INSERT INTO tableName (movie, released) VALUES ('El Halcón Maltés', '99');
INSERT INTO tableName (movie, released) VALUES ('Blade Runner', '100');
INSERT INTO tableName (movie, released) VALUES ('París, Texas', '101');
INSERT INTO tableName (movie, released) VALUES ('El Resplandor', '102');
INSERT INTO tableName (movie, released) VALUES ('La Naranja Mecánica', '103');
INSERT INTO tableName (movie, released) VALUES ('Los Mejores Años de Nuestra Vida', '104');
INSERT INTO tableName (movie, released) VALUES ('Fargo', '105');
INSERT INTO tableName (movie, released) VALUES ('Reservoir Dogs', '106');
INSERT INTO tableName (movie, released) VALUES ('Sin Perdón', '107');
INSERT INTO tableName (movie, released) VALUES ('Mi Vecino Totoro', '108');
INSERT INTO tableName (movie, released) VALUES ('Grupo Salvaje', '109');
INSERT INTO tableName (movie, released) VALUES ('Memento', '110');
INSERT INTO tableName (movie, released) VALUES ('El Pianista', '111');
INSERT INTO tableName (movie, released) VALUES ('Las Alas del Deseo', '112');
INSERT INTO tableName (movie, released) VALUES ('La Regla del Juego', '113');
INSERT INTO tableName (movie, released) VALUES ('Encadenados', '114');
INSERT INTO tableName (movie, released) VALUES ('La Strada', '115');
INSERT INTO tableName (movie, released) VALUES ('Aguirre, La Ira de Dios', '116');
INSERT INTO tableName (movie, released) VALUES ('La Leyenda del Indomable', '117');
INSERT INTO tableName (movie, released) VALUES ('Malas Tierras', '118');
INSERT INTO tableName (movie, released) VALUES ('Brazil', '119');
INSERT INTO tableName (movie, released) VALUES ('Solaris', '120');
INSERT INTO tableName (movie, released) VALUES ('Testigo de Cargo', '121');
INSERT INTO tableName (movie, released) VALUES ('La Conversación', '122');
INSERT INTO tableName (movie, released) VALUES ('Rebeca', '123');
INSERT INTO tableName (movie, released) VALUES ('Las Zapatillas Rojas', '124');
INSERT INTO tableName (movie, released) VALUES ('Deseando Amar', '125');
INSERT INTO tableName (movie, released) VALUES ('Las Noches de Cabiria', '126');
INSERT INTO tableName (movie, released) VALUES ('Tres Colores: Azuk', '127');
INSERT INTO tableName (movie, released) VALUES ('El Rey León', '128');
INSERT INTO tableName (movie, released) VALUES ('Masacre', '129');
INSERT INTO tableName (movie, released) VALUES ('12 Años de Esclavitud', '130');
INSERT INTO tableName (movie, released) VALUES ('Matar a Um Ruiseñor', '131');
INSERT INTO tableName (movie, released) VALUES ('Érase uma Vez em América', '132');
INSERT INTO tableName (movie, released) VALUES ('Las Diabólicas', '133');
INSERT INTO tableName (movie, released) VALUES ('Up', '134');
INSERT INTO tableName (movie, released) VALUES ('La Princesa Mononoke', '135');
INSERT INTO tableName (movie, released) VALUES ('Centauros del Desierto', '136');
INSERT INTO tableName (movie, released) VALUES ('El Gabinete del Dr. Caligari', '137');
INSERT INTO tableName (movie, released) VALUES ('Barry Lyndon', '138');
INSERT INTO tableName (movie, released) VALUES ('Lo que el Viento se Llevó', '139');
INSERT INTO tableName (movie, released) VALUES ('Las Uvas de la Ira', '140');
INSERT INTO tableName (movie, released) VALUES ('Antes del Atardecer', '141');
INSERT INTO tableName (movie, released) VALUES ('El Golpe', '142');
INSERT INTO tableName (movie, released) VALUES ('Todos los Hombres del Presidente', '143');
INSERT INTO tableName (movie, released) VALUES ('Los Sospechosos de Siempre', '144');
INSERT INTO tableName (movie, released) VALUES ('Pozos de Ambición', '145');
INSERT INTO tableName (movie, released) VALUES ('Whiplash', '146');
INSERT INTO tableName (movie, released) VALUES ('Al Final de la Escapada', '147');
INSERT INTO tableName (movie, released) VALUES ('Extraños em um Tren', '148');
INSERT INTO tableName (movie, released) VALUES ('El Buscavidas', '149');
INSERT INTO tableName (movie, released) VALUES ('Seven', '150');
INSERT INTO tableName (movie, released) VALUES ('Infiltrados', '151');
INSERT INTO tableName (movie, released) VALUES ('El Cazador', '152');
INSERT INTO tableName (movie, released) VALUES ('Haz lo que Debas', '153');
INSERT INTO tableName (movie, released) VALUES ('Network, um Mundo Implacable', '154');
INSERT INTO tableName (movie, released) VALUES ('El Mensajero del Miedo', '155');
INSERT INTO tableName (movie, released) VALUES ('Terminator 2', '156');
INSERT INTO tableName (movie, released) VALUES ('El Sueño Eterno', '157');
INSERT INTO tableName (movie, released) VALUES ('American Beauty', '158');
INSERT INTO tableName (movie, released) VALUES ('Amelie', '159');
INSERT INTO tableName (movie, released) VALUES ('Ocho Sentencias de Muerte', '160');
INSERT INTO tableName (movie, released) VALUES ('Historias de Filadelfia', '161');
INSERT INTO tableName (movie, released) VALUES ('Antes del Amanecer', '162');
INSERT INTO tableName (movie, released) VALUES ('No es País para Viejos', '163');
INSERT INTO tableName (movie, released) VALUES ('El Club de la Pelea', '164');
INSERT INTO tableName (movie, released) VALUES ('Manhattan', '165');
INSERT INTO tableName (movie, released) VALUES ('El Origen', '166');
INSERT INTO tableName (movie, released) VALUES ('Nacido para Matar', '167');
INSERT INTO tableName (movie, released) VALUES ('Chantaje em Broadway', '168');
INSERT INTO tableName (movie, released) VALUES ('Quien teme a Virginia Woolf?', '169');
INSERT INTO tableName (movie, released) VALUES ('El Odio', '170');
INSERT INTO tableName (movie, released) VALUES ('Tarde de Perros', '171');
INSERT INTO tableName (movie, released) VALUES ('La Última Película', '172');
INSERT INTO tableName (movie, released) VALUES ('Celebración', '173');
INSERT INTO tableName (movie, released) VALUES ('This is Spinal Tap', '174');
INSERT INTO tableName (movie, released) VALUES ('El Silencio de um Hombre', '175');
INSERT INTO tableName (movie, released) VALUES ('Dias del Cielo', '176');
INSERT INTO tableName (movie, released) VALUES ('La Semilla del Diablo', '177');
INSERT INTO tableName (movie, released) VALUES ('Caballero sin Espada', '178');
INSERT INTO tableName (movie, released) VALUES ('Anatomía de un Asesinato', '179');
INSERT INTO tableName (movie, released) VALUES ('Luna Nueva', '180');
INSERT INTO tableName (movie, released) VALUES ('El Hombre que Mató a Liberty Valance', '181');
INSERT INTO tableName (movie, released) VALUES ('French Connection', '182');
INSERT INTO tableName (movie, released) VALUES ('Rififi', '183');
INSERT INTO tableName (movie, released) VALUES ('Duro de Matar', '184');
INSERT INTO tableName (movie, released) VALUES ('El Acorazado Potemkin', '185');
INSERT INTO tableName (movie, released) VALUES ('Héroes de Ocasión', '186');
INSERT INTO tableName (movie, released) VALUES ('Atraco Perfecto', '187');
INSERT INTO tableName (movie, released) VALUES ('Solo Ante el Peligro', '188');
INSERT INTO tableName (movie, released) VALUES ('Buscado a Nemo', '189');
INSERT INTO tableName (movie, released) VALUES ('Déjame Entrar', '190');
INSERT INTO tableName (movie, released) VALUES ('Intensamente', '191');
INSERT INTO tableName (movie, released) VALUES ('Río Bravo', '192');
INSERT INTO tableName (movie, released) VALUES ('Old Boy', '193');
INSERT INTO tableName (movie, released) VALUES ('La Princesa Prometida', '194');
INSERT INTO tableName (movie, released) VALUES ('Patton', '195');
INSERT INTO tableName (movie, released) VALUES ('Los Niños del Paraíso', '196');
INSERT INTO tableName (movie, released) VALUES ('Cuentos de la Luna Pálida', '197');
INSERT INTO tableName (movie, released) VALUES ('Trono de Sangre', '198');
INSERT INTO tableName (movie, released) VALUES ('Harakiri', '199');
INSERT INTO tableName (movie, released) VALUES ('El Hundimiento', '200');
INSERT INTO tableName (movie, released) VALUES ('El Gran Escape', '201');
INSERT INTO tableName (movie, released) VALUES ('La Vida de Brian', '202');
INSERT INTO tableName (movie, released) VALUES ('Vacaciones em Roma', '203');
INSERT INTO tableName (movie, released) VALUES ('Ser o no Ser', '204');
INSERT INTO tableName (movie, released) VALUES ('Sin Novedad en el Frente', '205');
INSERT INTO tableName (movie, released) VALUES ('Djando Desencadenado', '206');
INSERT INTO tableName (movie, released) VALUES ('Mad Max: Furia en la Carretera', '207');
INSERT INTO tableName (movie, released) VALUES ('Primavera, Verano, Otoño, Invierno... Y Primavera', '208');
INSERT INTO tableName (movie, released) VALUES ('Trainspotting', '209');
INSERT INTO tableName (movie, released) VALUES ('El Ejército de las Sombras', '210');
INSERT INTO tableName (movie, released) VALUES ('Um Tranvía Llamado Deseo', '211');
INSERT INTO tableName (movie, released) VALUES ('Roma, Ciudad Abierta', '212');
INSERT INTO tableName (movie, released) VALUES ('La Red Social', '213');
INSERT INTO tableName (movie, released) VALUES ('Robin de los Bosques', '214');
INSERT INTO tableName (movie, released) VALUES ('La Muerte Tenía um Precio', '215');
INSERT INTO tableName (movie, released) VALUES ('El Discurso del Rey', '216');
INSERT INTO tableName (movie, released) VALUES ('El Espejo', '217');
INSERT INTO tableName (movie, released) VALUES ('Um Condenado a Muerte se ha Escapado', '218');
INSERT INTO tableName (movie, released) VALUES ('El Joven Frankenstein', '219');
INSERT INTO tableName (movie, released) VALUES ('Los Viajes de Sullivan', '220');
INSERT INTO tableName (movie, released) VALUES ('El Hombre Elefante', '221');
INSERT INTO tableName (movie, released) VALUES ('Terciopelo Azul', '222');
INSERT INTO tableName (movie, released) VALUES ('Laura', '223');
INSERT INTO tableName (movie, released) VALUES ('Adiós, Muchados', '224');
INSERT INTO tableName (movie, released) VALUES ('Forrest Gump', '225');
INSERT INTO tableName (movie, released) VALUES ('El Graduado', '226');
INSERT INTO tableName (movie, released) VALUES ('La Sombra de una Duda', '227');
INSERT INTO tableName (movie, released) VALUES ('La Escafandra y La Mariposa', '228');
INSERT INTO tableName (movie, released) VALUES ('Viridiana', '229');
INSERT INTO tableName (movie, released) VALUES ('Incendies', '230');
INSERT INTO tableName (movie, released) VALUES ('Boyhood', '231');
INSERT INTO tableName (movie, released) VALUES ('Terminator', '232');
INSERT INTO tableName (movie, released) VALUES ('Chungking Express', '233');
INSERT INTO tableName (movie, released) VALUES ('Dos Hombres y Um Destino', '234');
INSERT INTO tableName (movie, released) VALUES ('La La Land', '235');
INSERT INTO tableName (movie, released) VALUES ('La Muerte de los Hombres Vivientes', '236');
INSERT INTO tableName (movie, released) VALUES ('Paddington', '237');
INSERT INTO tableName (movie, released) VALUES ('La Fiera de mi Niña', '238');
INSERT INTO tableName (movie, released) VALUES ('Mary and Max', '239');
INSERT INTO tableName (movie, released) VALUES ('Como Entrenar a tu Dragón', '240');
INSERT INTO tableName (movie, released) VALUES ('El Ángel Exterminador', '241');
INSERT INTO tableName (movie, released) VALUES ('Um Profeta', '242');
INSERT INTO tableName (movie, released) VALUES ('La Vida es Bella', '243');
INSERT INTO tableName (movie, released) VALUES ('Amores Perros', '244');
INSERT INTO tableName (movie, released) VALUES ('Matrix', '245');
INSERT INTO tableName (movie, released) VALUES ('Heat', '246');
INSERT INTO tableName (movie, released) VALUES ('Ratatouille', '247');
INSERT INTO tableName (movie, released) VALUES ('Todo Sobre mi Madre', '248');
INSERT INTO tableName (movie, released) VALUES ('Antes del Anochecer', '249');
INSERT INTO tableName (movie, released) VALUES ('Nosferatu', '250');
INSERT INTO tableName (movie, released) VALUES ('El Secreto de tus Ojos', '251');
INSERT INTO tableName (movie, released) VALUES ('Persépolis', '252');
INSERT INTO tableName (movie, released) VALUES ('Memorias de um Asesino', '253');
INSERT INTO tableName (movie, released) VALUES ('El Intendente Sansho', '254');
INSERT INTO tableName (movie, released) VALUES ('Hannah y sus Hermanas', '255');
INSERT INTO tableName (movie, released) VALUES ('Bienvenido Mr. Chance', '256');
INSERT INTO tableName (movie, released) VALUES ('El Asesino', '257');
INSERT INTO tableName (movie, released) VALUES ('The Artist', '258');
INSERT INTO tableName (movie, released) VALUES ('El Gatopardo', '259');
INSERT INTO tableName (movie, released) VALUES ('Bonnie and Clyde', '260');
INSERT INTO tableName (movie, released) VALUES ('El Conformista', '261');
INSERT INTO tableName (movie, released) VALUES ('Lagaan: Érase uma Vez em la Índia', '262');
INSERT INTO tableName (movie, released) VALUES ('Elegiddos para la Glória', '263');
INSERT INTO tableName (movie, released) VALUES ('Harry Potter y las Reliquias de la Muerte', '264');
INSERT INTO tableName (movie, released) VALUES ('Hable con Ella', '265');
INSERT INTO tableName (movie, released) VALUES ('Uma Historia Sencilla', '266');
INSERT INTO tableName (movie, released) VALUES ('La Novia de Frankenstein', '267');
INSERT INTO tableName (movie, released) VALUES ('Indiana Jones y la Última Cruzada', '268');
INSERT INTO tableName (movie, released) VALUES ('Em Busca del Destino', '269');
INSERT INTO tableName (movie, released) VALUES ('King Kong', '270');
INSERT INTO tableName (movie, released) VALUES ('Las Vidas de Grace', '271');
INSERT INTO tableName (movie, released) VALUES ('La Bella y la Bestia', '272');
INSERT INTO tableName (movie, released) VALUES ('Pather Panchali', '273');
INSERT INTO tableName (movie, released) VALUES ('A Hard Day´s Night', '274');
INSERT INTO tableName (movie, released) VALUES ('Ordet', '275');
INSERT INTO tableName (movie, released) VALUES ('El Doctor Frankenstein', '276');
INSERT INTO tableName (movie, released) VALUES ('Repulsión', '277');
INSERT INTO tableName (movie, released) VALUES ('La Diligência', '278');
INSERT INTO tableName (movie, released) VALUES ('Juego Sucio', '279');
INSERT INTO tableName (movie, released) VALUES ('Toy Story 2', '280');
INSERT INTO tableName (movie, released) VALUES ('E.T. El Extraterrestre', '281');
INSERT INTO tableName (movie, released) VALUES ('Parque Jurásico', '282');
INSERT INTO tableName (movie, released) VALUES ('American History X', '283');
INSERT INTO tableName (movie, released) VALUES ('El Gigante de Hierro', '284');
INSERT INTO tableName (movie, released) VALUES ('La Mujer de la Arena', '285');
INSERT INTO tableName (movie, released) VALUES ('El Discreto Encanto de la Burguesía', '286');
INSERT INTO tableName (movie, released) VALUES ('4 Meses, 3 Semanas, 2 Días', '287');
INSERT INTO tableName (movie, released) VALUES ('Halloween', '288');
INSERT INTO tableName (movie, released) VALUES ('La Aventura', '289');
INSERT INTO tableName (movie, released) VALUES ('El Castillo Ambulante', '290');
INSERT INTO tableName (movie, released) VALUES ('Harold y Maude', '291');
INSERT INTO tableName (movie, released) VALUES ('El Infierno del Odio', '292');
INSERT INTO tableName (movie, released) VALUES ('Secretos y Mentiras', '293');
INSERT INTO tableName (movie, released) VALUES ('Encuentros Cercanos del Tercer Tipo', '294');
INSERT INTO tableName (movie, released) VALUES ('Jules y Jim', '295');
INSERT INTO tableName (movie, released) VALUES ('Cuenta Conmigo', '296');
INSERT INTO tableName (movie, released) VALUES ('La Soga', '297');
INSERT INTO tableName (movie, released) VALUES ('Once', '298');
INSERT INTO tableName (movie, released) VALUES ('Breve Encuentro', '299');
INSERT INTO tableName (movie, released) VALUES ('Em el Nombre del Padre', '300');
INSERT INTO tableName (movie, released) VALUES ('Retorno al Pasado', '301');
INSERT INTO tableName (movie, released) VALUES ('Monsters Inc.', '302');
INSERT INTO tableName (movie, released) VALUES ('El Tigre y Dragón', '303');
INSERT INTO tableName (movie, released) VALUES ('En el Calor de la Noche', '304');
INSERT INTO tableName (movie, released) VALUES ('Cowboy de Medianoche', '305');
INSERT INTO tableName (movie, released) VALUES ('Amor', '306');
INSERT INTO tableName (movie, released) VALUES ('Traidor en el Infierno', '307');
INSERT INTO tableName (movie, released) VALUES ('Akira', '308');
INSERT INTO tableName (movie, released) VALUES ('Los Vengadores', '309');
INSERT INTO tableName (movie, released) VALUES ('Gravity', '310');
INSERT INTO tableName (movie, released) VALUES ('Por Um Puñado de Dólares', '311');
INSERT INTO tableName (movie, released) VALUES ('Resplandor en la Noche', '312');
INSERT INTO tableName (movie, released) VALUES ('La Cosa', '313');
INSERT INTO tableName (movie, released) VALUES ('Nausicaä del Valle del Viento', '314');
INSERT INTO tableName (movie, released) VALUES ('El Exorcista', '315');
INSERT INTO tableName (movie, released) VALUES ('Requiém por um Sueño', '316');
INSERT INTO tableName (movie, released) VALUES ('3 Idiots', '317');
INSERT INTO tableName (movie, released) VALUES ('The Truman Show', '318');
INSERT INTO tableName (movie, released) VALUES ('Malditos Bastardos', '319');
INSERT INTO tableName (movie, released) VALUES ('Hiroshima Mon Amour', '320');
INSERT INTO tableName (movie, released) VALUES ('El Luchador', '321');
INSERT INTO tableName (movie, released) VALUES ('Zombies Party', '322');
INSERT INTO tableName (movie, released) VALUES ('Her', '323');
INSERT INTO tableName (movie, released) VALUES ('Platoon', '324');
INSERT INTO tableName (movie, released) VALUES ('Gans of Wasseypur', '325');
INSERT INTO tableName (movie, released) VALUES ('El Gran Hotel Budapest', '326');
INSERT INTO tableName (movie, released) VALUES ('Delitos y Faltas', '327');
INSERT INTO tableName (movie, released) VALUES ('El Dilema', '328');
INSERT INTO tableName (movie, released) VALUES ('El Castillo en el Cielo', '329');
INSERT INTO tableName (movie, released) VALUES ('El Profesional', '330');
INSERT INTO tableName (movie, released) VALUES ('Umberto D.', '331');
INSERT INTO tableName (movie, released) VALUES ('Yi Yi', '332');
INSERT INTO tableName (movie, released) VALUES ('Niños del Hombre', '333');
INSERT INTO tableName (movie, released) VALUES ('Días sin Huella', '334');
INSERT INTO tableName (movie, released) VALUES ('Zombies Party', '335');
INSERT INTO tableName (movie, released) VALUES ('Star Trek', '336');
INSERT INTO tableName (movie, released) VALUES ('El Cabellero Oscuro: La leyenda Renace', '337');
INSERT INTO tableName (movie, released) VALUES ('Pesadilla Antes de Navidad', '338');
INSERT INTO tableName (movie, released) VALUES ('Éxito a Cualquier Precio', '339');
INSERT INTO tableName (movie, released) VALUES ('Academia Rushmore', '340');
INSERT INTO tableName (movie, released) VALUES ('Ben-Hur', '341');
INSERT INTO tableName (movie, released) VALUES ('El Ultimátum de Bourne', '342');
INSERT INTO tableName (movie, released) VALUES ('Gandhi', '343');
INSERT INTO tableName (movie, released) VALUES ('Rompiendo las Ollas', '344');
INSERT INTO tableName (movie, released) VALUES ('Uma Mujer Bajo la Influencia', '345');
INSERT INTO tableName (movie, released) VALUES ('Bella de Día', '346');
INSERT INTO tableName (movie, released) VALUES ('A Vida o Muerte', '347');
INSERT INTO tableName (movie, released) VALUES ('Rebelde sin Causa', '348');
INSERT INTO tableName (movie, released) VALUES ('El Regreso', '349');
INSERT INTO tableName (movie, released) VALUES ('Al Rojo Vivo', '350');
INSERT INTO tableName (movie, released) VALUES ('Cómo ser John Malkovich', '351');
INSERT INTO tableName (movie, released) VALUES ('Cabaret', '352');
INSERT INTO tableName (movie, released) VALUES ('La Linterna Roja', '353');
INSERT INTO tableName (movie, released) VALUES ('Underground', '354');
INSERT INTO tableName (movie, released) VALUES ('Million Dollar Baby', '355');
INSERT INTO tableName (movie, released) VALUES ('Playtime', '356');
INSERT INTO tableName (movie, released) VALUES ('Hechizo de Tiempo', '357');
INSERT INTO tableName (movie, released) VALUES ('Withnail y Yo', '358');
INSERT INTO tableName (movie, released) VALUES ('Muerte entre las Flores', '359');
INSERT INTO tableName (movie, released) VALUES ('Argo', '360');
INSERT INTO tableName (movie, released) VALUES ('Boogie Nights', '361');
INSERT INTO tableName (movie, released) VALUES ('IP Man', '362');
INSERT INTO tableName (movie, released) VALUES ('Aladdín', '363');
INSERT INTO tableName (movie, released) VALUES ('Ghost in the Shell', '364');
INSERT INTO tableName (movie, released) VALUES ('La Parada de los Monstruos', '365');
INSERT INTO tableName (movie, released) VALUES ('Charada', '366');
INSERT INTO tableName (movie, released) VALUES ('El Hombre Mosca', '367');
INSERT INTO tableName (movie, released) VALUES ('La Reina de África', '368');
INSERT INTO tableName (movie, released) VALUES ('La Cena de los Acusados', '369');
INSERT INTO tableName (movie, released) VALUES ('Nicky, La Aprendiz de Bruja', '370');
INSERT INTO tableName (movie, released) VALUES ('Casino Royale', '371');
INSERT INTO tableName (movie, released) VALUES ('Moonrise Kindgdom', '372');
INSERT INTO tableName (movie, released) VALUES ('Hotel Rwanda', '373');
INSERT INTO tableName (movie, released) VALUES ('Gritos y Susurros', '374');
INSERT INTO tableName (movie, released) VALUES ('Lo que Queda del Día', '375');
INSERT INTO tableName (movie, released) VALUES ('Casi Famosos', '376');
INSERT INTO tableName (movie, released) VALUES ('Mommy', '377');
INSERT INTO tableName (movie, released) VALUES ('Mulholland Drive', '378');
INSERT INTO tableName (movie, released) VALUES ('Slumdog Millionaire', '379');
INSERT INTO tableName (movie, released) VALUES ('Alarma en el Expreso', '380');
INSERT INTO tableName (movie, released) VALUES ('Calles Salvajes', '381');
INSERT INTO tableName (movie, released) VALUES ('Y Dónde está el Piloto', '382');
INSERT INTO tableName (movie, released) VALUES ('Noche Alucinante', '383');
INSERT INTO tableName (movie, released) VALUES ('39 Escalones', '384');
INSERT INTO tableName (movie, released) VALUES ('El Gran Carnaval', '385');
INSERT INTO tableName (movie, released) VALUES ('La Vida Eléctrica de Louis Wain', '386');
INSERT INTO tableName (movie, released) VALUES ('Vencedores o Vencidos', '387');
INSERT INTO tableName (movie, released) VALUES ('Magnolia', '388');
INSERT INTO tableName (movie, released) VALUES ('James Bond contra Goldfinger', '389');
INSERT INTO tableName (movie, released) VALUES ('Batman Begins', '390');
INSERT INTO tableName (movie, released) VALUES ('Lost in Translation', '391');
INSERT INTO tableName (movie, released) VALUES ('Uma Noche em la Ópera', '392');
INSERT INTO tableName (movie, released) VALUES ('Espartaco', '393');
INSERT INTO tableName (movie, released) VALUES ('Arsénico y Encaje Antiguo', '394');
INSERT INTO tableName (movie, released) VALUES ('El Truco Final', '395');
INSERT INTO tableName (movie, released) VALUES ('La Evasión', '396');
INSERT INTO tableName (movie, released) VALUES ('El Bazar de las Sorpresas', '397');
INSERT INTO tableName (movie, released) VALUES ('Simplemente Sangre', '398');
INSERT INTO tableName (movie, released) VALUES ('Muertos Vivos', '399');
INSERT INTO tableName (movie, released) VALUES ('Mi Pie Izquierdo', '400');
INSERT INTO tableName (movie, released) VALUES ('Annette', '401');
INSERT INTO tableName (movie, released) VALUES ('Quién Engañó a Roger Rabbit?', '402');
INSERT INTO tableName (movie, released) VALUES ('Los Increíbles', '403');
INSERT INTO tableName (movie, released) VALUES ('Amarcord', '404');
INSERT INTO tableName (movie, released) VALUES ('13 Asesinos', '405');
INSERT INTO tableName (movie, released) VALUES ('Sentido y Sensibilidad', '406');
INSERT INTO tableName (movie, released) VALUES ('Star Wars: Episodio VI - El Retorno del Jedi', '407');
INSERT INTO tableName (movie, released) VALUES ('Arma Fatal', '408');
INSERT INTO tableName (movie, released) VALUES ('La Mejor Juventud', '409');
INSERT INTO tableName (movie, released) VALUES ('Drive', '410');
INSERT INTO tableName (movie, released) VALUES ('La Novicia Rebelde', '411');
INSERT INTO tableName (movie, released) VALUES ('Y Tu Mamá También', '412');
INSERT INTO tableName (movie, released) VALUES ('Los Cazafantasmas', '413');
INSERT INTO tableName (movie, released) VALUES ('Fantasía', '414');
INSERT INTO tableName (movie, released) VALUES ('Guardiones de la Galaxia', '415');
INSERT INTO tableName (movie, released) VALUES ('Intocable', '416');
INSERT INTO tableName (movie, released) VALUES ('Movida del 76', '417');
INSERT INTO tableName (movie, released) VALUES ('Kubo y las Cuerdas Mágicas', '418');
INSERT INTO tableName (movie, released) VALUES ('Cartas desde Iwo Jima', '419');
INSERT INTO tableName (movie, released) VALUES ('Ultimátum a la Tierra', '420');
INSERT INTO tableName (movie, released) VALUES ('La Noche Americana', '421');
INSERT INTO tableName (movie, released) VALUES ('En Tierra Hostil', '422');
INSERT INTO tableName (movie, released) VALUES ('Bienvenidos a Belleville', '423');
INSERT INTO tableName (movie, released) VALUES ('La Milla Verde', '424');
INSERT INTO tableName (movie, released) VALUES ('Parásitos', '425');
INSERT INTO tableName (movie, released) VALUES ('Nashville', '426');
INSERT INTO tableName (movie, released) VALUES ('El Espíritu de la Colmena', '427');
INSERT INTO tableName (movie, released) VALUES ('Crimen Perfecto', '428');
INSERT INTO tableName (movie, released) VALUES ('Cisne Negro', '429');
INSERT INTO tableName (movie, released) VALUES ('Los Gritos del Silencio', '430');
INSERT INTO tableName (movie, released) VALUES ('Taare Zameen Par', '431');
INSERT INTO tableName (movie, released) VALUES ('Harry El Sucio', '432');
INSERT INTO tableName (movie, released) VALUES ('El Rey de la Comedia', '433');
INSERT INTO tableName (movie, released) VALUES ('Iron Man', '434');
INSERT INTO tableName (movie, released) VALUES ('Los Chicos del Barrio', '435');
INSERT INTO tableName (movie, released) VALUES ('El Sexto Sentido', '436');
INSERT INTO tableName (movie, released) VALUES ('Fantástico Sr. Fox', '437');
INSERT INTO tableName (movie, released) VALUES ('Rang de Basanti', '438');
INSERT INTO tableName (movie, released) VALUES ('Tropa de Élite 2', '439');
INSERT INTO tableName (movie, released) VALUES ('El Juego de Hollywood', '440');
INSERT INTO tableName (movie, released) VALUES ('El Fugitivo', '441');
INSERT INTO tableName (movie, released) VALUES ('Las Tres Noches de Eva', '442');
INSERT INTO tableName (movie, released) VALUES ('Casino', '443');
INSERT INTO tableName (movie, released) VALUES ('La Vida de Adéle', '444');
INSERT INTO tableName (movie, released) VALUES ('My Fair Lady', '445');
INSERT INTO tableName (movie, released) VALUES ('Historias de Navidad', '446');
INSERT INTO tableName (movie, released) VALUES ('Serpico', '447');
INSERT INTO tableName (movie, released) VALUES ('Into the Wild', '448');
INSERT INTO tableName (movie, released) VALUES ('El Culto Siniestro', '449');
INSERT INTO tableName (movie, released) VALUES ('Barton Fink', '450');
INSERT INTO tableName (movie, released) VALUES ('Mary Poppins', '451');
INSERT INTO tableName (movie, released) VALUES ('El Hombre de al Lado', '452');
INSERT INTO tableName (movie, released) VALUES ('This is England', '453');
INSERT INTO tableName (movie, released) VALUES ('Ed Wood', '454');
INSERT INTO tableName (movie, released) VALUES ('La Lego Película', '455');
INSERT INTO tableName (movie, released) VALUES ('Operación Dragón', '456');
INSERT INTO tableName (movie, released) VALUES ('Mad Max 2: El Guerrero de la Carretera', '457');
INSERT INTO tableName (movie, released) VALUES ('JFK', '458');
INSERT INTO tableName (movie, released) VALUES ('Rain Man', '459');
INSERT INTO tableName (movie, released) VALUES ('Moon', '460');
INSERT INTO tableName (movie, released) VALUES ('Los Pájaros', '461');
INSERT INTO tableName (movie, released) VALUES ('Fitzcarraldo', '462');
INSERT INTO tableName (movie, released) VALUES ('Hierro 3', '463');
INSERT INTO tableName (movie, released) VALUES ('El Club de los Cinco', '464');
INSERT INTO tableName (movie, released) VALUES ('Cruella', '465');
INSERT INTO tableName (movie, released) VALUES ('Capitán Phillips', '466');
INSERT INTO tableName (movie, released) VALUES ('Doce Monos', '467');
INSERT INTO tableName (movie, released) VALUES ('Atrápame si Puedes', '468');
INSERT INTO tableName (movie, released) VALUES ('Suspira', '469');
INSERT INTO tableName (movie, released) VALUES ('Skyfall', '470');
INSERT INTO tableName (movie, released) VALUES ('Cuando Pasan las Cigüeñas', '471');
INSERT INTO tableName (movie, released) VALUES ('El Joven Manos de Tijeras', '472');
INSERT INTO tableName (movie, released) VALUES ('El Fotógrafo de Pánico', '473');
INSERT INTO tableName (movie, released) VALUES ('Qué fue de Baby James?', '474');
INSERT INTO tableName (movie, released) VALUES ('Temple de Acero', '475');
INSERT INTO tableName (movie, released) VALUES ('El Ladrón de Orquídeas', '476');
INSERT INTO tableName (movie, released) VALUES ('Tiempos de Gloria', '477');
INSERT INTO tableName (movie, released) VALUES ('Cabeza Borradora', '478');
INSERT INTO tableName (movie, released) VALUES ('The Fighter', '479');
INSERT INTO tableName (movie, released) VALUES ('Pasión de los Fuertes', '480');
INSERT INTO tableName (movie, released) VALUES ('Contra la Pared', '481');
INSERT INTO tableName (movie, released) VALUES ('El Último Emperador', '482');
INSERT INTO tableName (movie, released) VALUES ('Mar Adentro', '483');
INSERT INTO tableName (movie, released) VALUES ('El Fugitivo Josey Wales', '484');
INSERT INTO tableName (movie, released) VALUES ('El Club de los Desahuciados', '485');
INSERT INTO tableName (movie, released) VALUES ('Relatos Salvajes', '486');
INSERT INTO tableName (movie, released) VALUES ('Gladiator', '487');
INSERT INTO tableName (movie, released) VALUES ('El Hombre que Sería Rey', '488');
INSERT INTO tableName (movie, released) VALUES ('Pickpocket', '489');
INSERT INTO tableName (movie, released) VALUES ('Pequeña Miss Sunshine', '490');
INSERT INTO tableName (movie, released) VALUES ('Kill Bill 2', '491');
INSERT INTO tableName (movie, released) VALUES ('Los Productores', '492');
INSERT INTO tableName (movie, released) VALUES ('Vías Cruzadas', '493');
INSERT INTO tableName (movie, released) VALUES ('Escape Salvaje', '494');
INSERT INTO tableName (movie, released) VALUES ('Volver', '495');
INSERT INTO tableName (movie, released) VALUES ('Bajo el Peso de la Ley', '496');
INSERT INTO tableName (movie, released) VALUES ('Battle Royale', '497');
INSERT INTO tableName (movie, released) VALUES ('Doce del Patíbulo', '498');
INSERT INTO tableName (movie, released) VALUES ('Brokeback Mountain', '499');
INSERT INTO tableName (movie, released) VALUES ('El Guasón', '500');
INSERT INTO tableName (movie, released) VALUES ('Narciso Negro', '501');
INSERT INTO tableName (movie, released) VALUES ('El Desprecio', '502');
INSERT INTO tableName (movie, released) VALUES ('El Lado Luminoso de La Vida', '503');
INSERT INTO tableName (movie, released) VALUES ('Hero', '504');
INSERT INTO tableName (movie, released) VALUES ('Rocco y sus Hermanos', '505');
INSERT INTO tableName (movie, released) VALUES ('Tener y no Tener', '506');
INSERT INTO tableName (movie, released) VALUES ('Shrek', '507');
INSERT INTO tableName (movie, released) VALUES ('Papillon', '508');
INSERT INTO tableName (movie, released) VALUES ('Deliverance', '509');
INSERT INTO tableName (movie, released) VALUES ('Gato Negro, Gato Blanco', '510');
INSERT INTO tableName (movie, released) VALUES ('El Piano', '511');
INSERT INTO tableName (movie, released) VALUES ('Em un Lugar Solitario', '512');
INSERT INTO tableName (movie, released) VALUES ('El Planeta de los Simios', '513');
INSERT INTO tableName (movie, released) VALUES ('M.A.S.H.', '514');
INSERT INTO tableName (movie, released) VALUES ('Primavera Tardía', '515');
INSERT INTO tableName (movie, released) VALUES ('Em Tierra de Nadie', '516');
INSERT INTO tableName (movie, released) VALUES ('Uma Historia del Bronx', '517');
INSERT INTO tableName (movie, released) VALUES ('Juno', '518');
INSERT INTO tableName (movie, released) VALUES ('Delicatessen', '519');
INSERT INTO tableName (movie, released) VALUES ('Distrito 9', '520');
INSERT INTO tableName (movie, released) VALUES ('Corre Lola, Corre', '521');
INSERT INTO tableName (movie, released) VALUES ('Doctor Zhivago', '522');
INSERT INTO tableName (movie, released) VALUES ('Perdida', '523');
INSERT INTO tableName (movie, released) VALUES ('The Beatles: Get Back', '524');
INSERT INTO tableName (movie, released) VALUES ('Kramer contra Kramer', '525');
INSERT INTO tableName (movie, released) VALUES ('Malcolm X', '526');
INSERT INTO tableName (movie, released) VALUES ('Star Trek II: La Ira de Khan', '527');
INSERT INTO tableName (movie, released) VALUES ('La Vida de Pi', '528');
INSERT INTO tableName (movie, released) VALUES ('Blancanieves y los Siete Enanitos', '529');
INSERT INTO tableName (movie, released) VALUES ('La Gata sobre el Tejado de Zinc', '530');
INSERT INTO tableName (movie, released) VALUES ('El Dulce Porvenir', '531');
INSERT INTO tableName (movie, released) VALUES ('Donnie Darko', '532');
INSERT INTO tableName (movie, released) VALUES ('Los Siete Magníficos', '533');
INSERT INTO tableName (movie, released) VALUES ('Rush', '534');
INSERT INTO tableName (movie, released) VALUES ('Luna de Papel', '535');
INSERT INTO tableName (movie, released) VALUES ('El Club de los Poetas Muertos', '536');
INSERT INTO tableName (movie, released) VALUES ('Nueve Reinas', '537');
INSERT INTO tableName (movie, released) VALUES ('Traffic', '538');
INSERT INTO tableName (movie, released) VALUES ('Quiz Show', '539');
INSERT INTO tableName (movie, released) VALUES ('West Side Story', '540');
INSERT INTO tableName (movie, released) VALUES ('La Doble Vida de Verónica', '541');
INSERT INTO tableName (movie, released) VALUES ('Cadenas Rotas', '542');
INSERT INTO tableName (movie, released) VALUES ('Serenity', '543');
INSERT INTO tableName (movie, released) VALUES ('El Invisible Harvey', '544');
INSERT INTO tableName (movie, released) VALUES ('Braveheart', '545');
INSERT INTO tableName (movie, released) VALUES ('Mi Nombre es Harvey Milk', '546');
INSERT INTO tableName (movie, released) VALUES ('Um Ladrón en la Alcoba', '547');
INSERT INTO tableName (movie, released) VALUES ('Moneyball', '548');
INSERT INTO tableName (movie, released) VALUES ('Drive my Car', '549');
INSERT INTO tableName (movie, released) VALUES ('American Graffiti', '550');
INSERT INTO tableName (movie, released) VALUES ('Lolita', '551');
INSERT INTO tableName (movie, released) VALUES ('X-Men: Días del Futuro Pasado', '552');
INSERT INTO tableName (movie, released) VALUES ('Blow-Up', '553');
INSERT INTO tableName (movie, released) VALUES ('Harry Potter y el Prisionero de Azkaban', '554');
INSERT INTO tableName (movie, released) VALUES ('Estación Central de Brasil', '555');
INSERT INTO tableName (movie, released) VALUES ('Midnight in Paris', '556');
INSERT INTO tableName (movie, released) VALUES ('Los Guerreros', '557');
INSERT INTO tableName (movie, released) VALUES ('Acvaricia', '558');
INSERT INTO tableName (movie, released) VALUES ('Las Ventajas de ser Invisible', '559');
INSERT INTO tableName (movie, released) VALUES ('El Último', '560');
INSERT INTO tableName (movie, released) VALUES ('Escondidos em Brujas', '561');
INSERT INTO tableName (movie, released) VALUES ('Orgullo y Prejuicio', '562');
INSERT INTO tableName (movie, released) VALUES ('Um Experto en Diversión', '563');
INSERT INTO tableName (movie, released) VALUES ('Nebraska', '564');
INSERT INTO tableName (movie, released) VALUES ('La Fortaleza Escondida', '565');
INSERT INTO tableName (movie, released) VALUES ('Kung Fu Sion', '566');
INSERT INTO tableName (movie, released) VALUES ('The Blues Brothers', '567');
INSERT INTO tableName (movie, released) VALUES ('Desayuno con Diamantes', '568');
INSERT INTO tableName (movie, released) VALUES ('Porco Rosso', '569');
INSERT INTO tableName (movie, released) VALUES ('Gran Torino', '570');
INSERT INTO tableName (movie, released) VALUES ('Paterson', '571');
INSERT INTO tableName (movie, released) VALUES ('Río Rojo', '572');
INSERT INTO tableName (movie, released) VALUES ('El Expressio de Medianoche', '573');
INSERT INTO tableName (movie, released) VALUES ('Sanjuro', '574');
INSERT INTO tableName (movie, released) VALUES ('United 93', '575');
INSERT INTO tableName (movie, released) VALUES ('Good bye, Lenin!', '576');
INSERT INTO tableName (movie, released) VALUES ('Alta Fidelidad', '577');
INSERT INTO tableName (movie, released) VALUES ('Los Intocables de Eliot Ness', '578');
INSERT INTO tableName (movie, released) VALUES ('Cuando Harry Conoció a Sally', '579');
INSERT INTO tableName (movie, released) VALUES ('Happiness', '580');
INSERT INTO tableName (movie, released) VALUES ('Huida a Medianoche', '581');
INSERT INTO tableName (movie, released) VALUES ('Kill Bill 1', '582');
INSERT INTO tableName (movie, released) VALUES ('La Mosca', '583');
INSERT INTO tableName (movie, released) VALUES ('Los Ojos sin Rostro', '584');
INSERT INTO tableName (movie, released) VALUES ('Orfeo', '585');
INSERT INTO tableName (movie, released) VALUES ('Como entrenar a tu Dragón 2', '586');
INSERT INTO tableName (movie, released) VALUES ('El Año Pasado en Marienbad', '587');
INSERT INTO tableName (movie, released) VALUES ('Un Segundo', '588');
INSERT INTO tableName (movie, released) VALUES ('Posesión Infernal', '589');
INSERT INTO tableName (movie, released) VALUES ('Rocky', '590');
INSERT INTO tableName (movie, released) VALUES ('El Irlandés', '591');
INSERT INTO tableName (movie, released) VALUES ('Niños del Paraísp', '592');
INSERT INTO tableName (movie, released) VALUES ('Ghost World', '593');
INSERT INTO tableName (movie, released) VALUES ('Río Místico', '594');
INSERT INTO tableName (movie, released) VALUES ('Shine', '595');
INSERT INTO tableName (movie, released) VALUES ('Hunger', '596');
INSERT INTO tableName (movie, released) VALUES ('Scarface', '597');
INSERT INTO tableName (movie, released) VALUES ('Los Paraguas de Cherburgo', '598');
INSERT INTO tableName (movie, released) VALUES ('Primicia Mortal', '599');
INSERT INTO tableName (movie, released) VALUES ('Enredados', '600');
INSERT INTO tableName (movie, released) VALUES ('El Hombre Tranquilo', '601');
INSERT INTO tableName (movie, released) VALUES ('El Viento se Levanta', '602');
INSERT INTO tableName (movie, released) VALUES ('El Lobo de Wall Street', '603');
INSERT INTO tableName (movie, released) VALUES ('After Hours', '604');
INSERT INTO tableName (movie, released) VALUES ('Armonías de Werckmeister', '605');
INSERT INTO tableName (movie, released) VALUES ('Apolo 13', '606');
INSERT INTO tableName (movie, released) VALUES ('Al Servicio de las Damas', '607');
INSERT INTO tableName (movie, released) VALUES ('La Noche más Oscura', '608');
INSERT INTO tableName (movie, released) VALUES ('El Pasado', '609');
INSERT INTO tableName (movie, released) VALUES ('Tiempo de Gitanos', '610');
INSERT INTO tableName (movie, released) VALUES ('Snatch: Cerdos y Diamantes', '611');
INSERT INTO tableName (movie, released) VALUES ('Mysterious Skin', '612');
INSERT INTO tableName (movie, released) VALUES ('Prisioneros', '613');
INSERT INTO tableName (movie, released) VALUES ('Control', '614');
INSERT INTO tableName (movie, released) VALUES ('La Invención de Hugo', '615');
INSERT INTO tableName (movie, released) VALUES ('Bailando com Lobos', '616');
INSERT INTO tableName (movie, released) VALUES ('Tres colores: Blanco', '617');
INSERT INTO tableName (movie, released) VALUES ('Celda 211', '618');
INSERT INTO tableName (movie, released) VALUES ('La Infancia de Iván', '619');
INSERT INTO tableName (movie, released) VALUES ('Un Mundo de Fantasía', '620');
INSERT INTO tableName (movie, released) VALUES ('Dolor y Gloria', '621');
INSERT INTO tableName (movie, released) VALUES ('Una Mente Maravillosa', '622');
INSERT INTO tableName (movie, released) VALUES ('Dogville', '623');
INSERT INTO tableName (movie, released) VALUES ('Al Azar de Baltasar', '624');
INSERT INTO tableName (movie, released) VALUES ('Venecia Rojo Shocking', '625');
INSERT INTO tableName (movie, released) VALUES ('De Aquí a la Eternidad', '626');
INSERT INTO tableName (movie, released) VALUES ('Clerks', '627');
INSERT INTO tableName (movie, released) VALUES ('El Último Mohicano', '628');
INSERT INTO tableName (movie, released) VALUES ('Pinocho', '629');
INSERT INTO tableName (movie, released) VALUES ('La Gran Belleza', '630');
INSERT INTO tableName (movie, released) VALUES ('Vidas Cruzadas', '631');
INSERT INTO tableName (movie, released) VALUES ('Um pez Llamado Wanda', '632');
INSERT INTO tableName (movie, released) VALUES ('Historia de un Matrimonio', '633');
INSERT INTO tableName (movie, released) VALUES ('American Splendor', '634');
INSERT INTO tableName (movie, released) VALUES ('Los Sobornados', '635');
INSERT INTO tableName (movie, released) VALUES ('Easy Rider. Buscando mi Destino', '636');
INSERT INTO tableName (movie, released) VALUES ('Colegio de Animales', '637');
INSERT INTO tableName (movie, released) VALUES ('La Matanza de Texas', '638');
INSERT INTO tableName (movie, released) VALUES ('Ponyo en el Acantilado', '639');
INSERT INTO tableName (movie, released) VALUES ('Al Este del Éden', '640');
INSERT INTO tableName (movie, released) VALUES ('Bailarina en la Oscuridad', '641');
INSERT INTO tableName (movie, released) VALUES ('Adiós Pequeña, Adiós', '642');
INSERT INTO tableName (movie, released) VALUES ('Desaparecida', '643');
INSERT INTO tableName (movie, released) VALUES ('Incidente en Ox-Bow', '644');
INSERT INTO tableName (movie, released) VALUES ('Robocop', '645');
INSERT INTO tableName (movie, released) VALUES ('Juegos, Trampas y Armas Humeantes', '646');
INSERT INTO tableName (movie, released) VALUES ('Arrietty y el Mundo de los Diminutos', '647');
INSERT INTO tableName (movie, released) VALUES ('Dunkerque', '648');
INSERT INTO tableName (movie, released) VALUES ('Fruitvale Station', '649');
INSERT INTO tableName (movie, released) VALUES ('Al Filo el Mañana', '650');
INSERT INTO tableName (movie, released) VALUES ('Pena de Muerte', '651');
INSERT INTO tableName (movie, released) VALUES ('Birdman', '652');
INSERT INTO tableName (movie, released) VALUES ('El Desafío - Frost contra Nixon', '653');
INSERT INTO tableName (movie, released) VALUES ('Los Excentricos Tenenbaums', '654');
INSERT INTO tableName (movie, released) VALUES ('Los Diez Mandamientos', '655');
INSERT INTO tableName (movie, released) VALUES ('Kagemusha', '656');
INSERT INTO tableName (movie, released) VALUES ('Looper', '657');
INSERT INTO tableName (movie, released) VALUES ('Misery', '658');
INSERT INTO tableName (movie, released) VALUES ('Diarios de Motocicleta', '659');
INSERT INTO tableName (movie, released) VALUES ('El Espinazo del Diablo', '660');
INSERT INTO tableName (movie, released) VALUES ('Amistades Peligrosas', '661');
INSERT INTO tableName (movie, released) VALUES ('La Cinta Blanca', '662');
INSERT INTO tableName (movie, released) VALUES ('The Raid', '663');
INSERT INTO tableName (movie, released) VALUES ('Picnic en Hanging Rock', '664');
INSERT INTO tableName (movie, released) VALUES ('Coco', '665');
INSERT INTO tableName (movie, released) VALUES ('Zodiac', '666');
INSERT INTO tableName (movie, released) VALUES ('El Circo', '667');
INSERT INTO tableName (movie, released) VALUES ('Fausto', '668');
INSERT INTO tableName (movie, released) VALUES ('La Crónica Francesa', '669');
INSERT INTO tableName (movie, released) VALUES ('Capitán América', '670');
INSERT INTO tableName (movie, released) VALUES ('If...', '671');
INSERT INTO tableName (movie, released) VALUES ('Outra Ronda', '672');
INSERT INTO tableName (movie, released) VALUES ('El Tren de las 3:10', '673');
INSERT INTO tableName (movie, released) VALUES ('Leaving Las Vegas', '674');
INSERT INTO tableName (movie, released) VALUES ('Entre Copas', '675');
INSERT INTO tableName (movie, released) VALUES ('A Propósito de llewyn Davis', '676');
INSERT INTO tableName (movie, released) VALUES ('La Delgada Línea Roja', '677');
INSERT INTO tableName (movie, released) VALUES ('Boys don´t Cry', '678');
INSERT INTO tableName (movie, released) VALUES ('The World of Apu', '679');
INSERT INTO tableName (movie, released) VALUES ('El Beso Mortal', '680');
INSERT INTO tableName (movie, released) VALUES ('Zelig', '681');
INSERT INTO tableName (movie, released) VALUES ('The Raid 2', '682');
INSERT INTO tableName (movie, released) VALUES ('Promesas del Este', '683');
INSERT INTO tableName (movie, released) VALUES ('Pesadilla em Elm Street', '684');
INSERT INTO tableName (movie, released) VALUES ('Bo Burnham: Inside', '685');
INSERT INTO tableName (movie, released) VALUES ('Mi Tío', '686');
INSERT INTO tableName (movie, released) VALUES ('La Sirenita', '687');
INSERT INTO tableName (movie, released) VALUES ('Expiación', '688');
INSERT INTO tableName (movie, released) VALUES ('Rompe Ralph!', '689');
INSERT INTO tableName (movie, released) VALUES ('Headhunters', '690');
INSERT INTO tableName (movie, released) VALUES ('El poder del Perro', '691');
INSERT INTO tableName (movie, released) VALUES ('La Rosa Púrpura de el Cairo', '692');
INSERT INTO tableName (movie, released) VALUES ('Sueño de Invierno', '693');
INSERT INTO tableName (movie, released) VALUES ('El Amanecer del Planeta de los Simios', '694');
INSERT INTO tableName (movie, released) VALUES ('El Color Púrpura', '695');
INSERT INTO tableName (movie, released) VALUES ('La Última Noche de Borris Grushenko', '696');
INSERT INTO tableName (movie, released) VALUES ('Haider', '697');
INSERT INTO tableName (movie, released) VALUES ('Nomadland', '698');
INSERT INTO tableName (movie, released) VALUES ('Avatar', '699');
INSERT INTO tableName (movie, released) VALUES ('Superman', '700');
INSERT INTO tableName (movie, released) VALUES ('Las Vacaciones del Señor Hulot', '701');
INSERT INTO tableName (movie, released) VALUES ('Desde Rusia con Amor', '702');
INSERT INTO tableName (movie, released) VALUES ('Truman Capote', '703');
INSERT INTO tableName (movie, released) VALUES ('Kiss Kiss, Bang Bang', '704');
INSERT INTO tableName (movie, released) VALUES ('Johnny Guitar', '705');
INSERT INTO tableName (movie, released) VALUES ('Philomena', '706');
INSERT INTO tableName (movie, released) VALUES ('En América', '707');
INSERT INTO tableName (movie, released) VALUES ('The Batman', '708');
INSERT INTO tableName (movie, released) VALUES ('Ninotchka', '709');
INSERT INTO tableName (movie, released) VALUES ('El Ocaso del Samurái', '710');
INSERT INTO tableName (movie, released) VALUES ('The Bourne Identity', '711');
INSERT INTO tableName (movie, released) VALUES ('Tootsie', '712');
INSERT INTO tableName (movie, released) VALUES ('Despedidas', '713');
INSERT INTO tableName (movie, released) VALUES ('Piratas del Caribe: La Maldición de la Perla Negra', '714');
INSERT INTO tableName (movie, released) VALUES ('Súper Cool', '715');
INSERT INTO tableName (movie, released) VALUES ('The Imitation Game', '716');
INSERT INTO tableName (movie, released) VALUES ('(500) Días Juntos', '717');
INSERT INTO tableName (movie, released) VALUES ('La Casa de Las Dagas Voladoras', '718');
INSERT INTO tableName (movie, released) VALUES ('Raíces Profundas', '719');
INSERT INTO tableName (movie, released) VALUES ('Millennium 1', '720');
INSERT INTO tableName (movie, released) VALUES ('Los Vividores', '721');
INSERT INTO tableName (movie, released) VALUES ('En La Cuerda Floja', '722');
INSERT INTO tableName (movie, released) VALUES ('Yo Vi al Diablo', '723');
INSERT INTO tableName (movie, released) VALUES ('Ida', '724');
INSERT INTO tableName (movie, released) VALUES ('Waking Life', '725');
INSERT INTO tableName (movie, released) VALUES ('Extraños en el Paraíso', '726');
INSERT INTO tableName (movie, released) VALUES ('Buenas Noches, y Buena Suerte', '727');
INSERT INTO tableName (movie, released) VALUES ('Y El Mundo Marcha', '728');
INSERT INTO tableName (movie, released) VALUES ('Carlito´s Way', '729');
INSERT INTO tableName (movie, released) VALUES ('Um Hombre Lobo Americano em Londres', '730');
INSERT INTO tableName (movie, released) VALUES ('Coda', '731');
INSERT INTO tableName (movie, released) VALUES ('REC', '732');
INSERT INTO tableName (movie, released) VALUES ('Paprika', '733');
INSERT INTO tableName (movie, released) VALUES ('Wallace & Gromit: La Maldición de Las Verduras', '734');
INSERT INTO tableName (movie, released) VALUES ('Los Juegos del Hambre: En Llamas', '735');
INSERT INTO tableName (movie, released) VALUES ('Very Important Perros', '736');
INSERT INTO tableName (movie, released) VALUES ('Flee', '737');
INSERT INTO tableName (movie, released) VALUES ('Election', '738');
INSERT INTO tableName (movie, released) VALUES ('El Imperio del Sol', '739');
INSERT INTO tableName (movie, released) VALUES ('A quien ama Gilbert Grape?', '740');
INSERT INTO tableName (movie, released) VALUES ('Abre los Ojos', '741');
INSERT INTO tableName (movie, released) VALUES ('The Town', '742');
INSERT INTO tableName (movie, released) VALUES ('Mientras la Ciudad Duerme', '743');
INSERT INTO tableName (movie, released) VALUES ('V de Vendetta', '744');
INSERT INTO tableName (movie, released) VALUES ('Sabrina', '745');
INSERT INTO tableName (movie, released) VALUES ('EL Heróe del Rio', '746');
INSERT INTO tableName (movie, released) VALUES ('Descubriendo el Amor', '747');
INSERT INTO tableName (movie, released) VALUES ('Hamlet', '748');
INSERT INTO tableName (movie, released) VALUES ('Donnie Brasco', '749');
INSERT INTO tableName (movie, released) VALUES ('Nada em Común', '750');
INSERT INTO tableName (movie, released) VALUES ('X-Men: First Class', '751');
INSERT INTO tableName (movie, released) VALUES ('Animal Kingdom', '752');
INSERT INTO tableName (movie, released) VALUES ('Lo que Hacemos en las Sombras', '753');
INSERT INTO tableName (movie, released) VALUES ('Planeta Prohibido', '754');
INSERT INTO tableName (movie, released) VALUES ('Carrie', '755');
INSERT INTO tableName (movie, released) VALUES ('Las Horas', '756');
INSERT INTO tableName (movie, released) VALUES ('Coraline', '757');
INSERT INTO tableName (movie, released) VALUES ('Lincoln', '758');
INSERT INTO tableName (movie, released) VALUES ('Marty', '759');
INSERT INTO tableName (movie, released) VALUES ('Mujeres al Borde de um Ataque de Nervios', '760');
INSERT INTO tableName (movie, released) VALUES ('Um Hombre Soltero', '761');
INSERT INTO tableName (movie, released) VALUES ('Enredos de Oficina', '762');
INSERT INTO tableName (movie, released) VALUES ('El Manantial de la Doncella', '763');
INSERT INTO tableName (movie, released) VALUES ('La Piel que Habito', '764');
INSERT INTO tableName (movie, released) VALUES ('Cielo de Octubre', '765');
INSERT INTO tableName (movie, released) VALUES ('Ex_Machina', '766');
INSERT INTO tableName (movie, released) VALUES ('La Ciudad de los Niños Perdidos', '767');
INSERT INTO tableName (movie, released) VALUES ('Historias Cruzadas', '768');
INSERT INTO tableName (movie, released) VALUES ('Star Trek: En la Oscuridad', '769');
INSERT INTO tableName (movie, released) VALUES ('Adiós a mi Concubina', '770');
INSERT INTO tableName (movie, released) VALUES ('South Park: Más Grande, Más Largo y Sin Cortes', '771');
INSERT INTO tableName (movie, released) VALUES ('Winter´s Bone', '772');
INSERT INTO tableName (movie, released) VALUES ('Logan', '773');
INSERT INTO tableName (movie, released) VALUES ('Minority Report', '774');
INSERT INTO tableName (movie, released) VALUES ('Scott Pilgrim Contra el Mundo', '775');
INSERT INTO tableName (movie, released) VALUES ('Up in the Air', '776');
INSERT INTO tableName (movie, released) VALUES ('Como en um Espejo', '777');
INSERT INTO tableName (movie, released) VALUES ('El Cuarto Mandamento', '778');
INSERT INTO tableName (movie, released) VALUES ('Frozen', '779');
INSERT INTO tableName (movie, released) VALUES ('O Brother!', '780');
INSERT INTO tableName (movie, released) VALUES ('Big Fish', '781');
INSERT INTO tableName (movie, released) VALUES ('Jojo Rabbit', '782');
INSERT INTO tableName (movie, released) VALUES ('Escuela de Jóvenes Asesinos', '783');
INSERT INTO tableName (movie, released) VALUES ('Big Hero 6', '784');
INSERT INTO tableName (movie, released) VALUES ('Esencia de Mujer', '785');
INSERT INTO tableName (movie, released) VALUES ('Spider-Man 2', '786');
INSERT INTO tableName (movie, released) VALUES ('Gente Corriente', '787');
INSERT INTO tableName (movie, released) VALUES ('El Mito de Bourne', '788');
INSERT INTO tableName (movie, released) VALUES ('Arizona Baby', '789');
INSERT INTO tableName (movie, released) VALUES ('Cayo Largo', '790');
INSERT INTO tableName (movie, released) VALUES ('Dead Alive', '791');
INSERT INTO tableName (movie, released) VALUES ('Historias de Familia', '792');
INSERT INTO tableName (movie, released) VALUES ('Sombrero de Copa', '793');
INSERT INTO tableName (movie, released) VALUES ('Los Descendientes', '794');
INSERT INTO tableName (movie, released) VALUES ('La Forma del Agua', '795');
INSERT INTO tableName (movie, released) VALUES ('Juegos Prohibidos', '796');
INSERT INTO tableName (movie, released) VALUES ('Cinderella Man', '797');
INSERT INTO tableName (movie, released) VALUES ('Grindhouse', '798');
INSERT INTO tableName (movie, released) VALUES ('Despertares', '799');
INSERT INTO tableName (movie, released) VALUES ('Intolerancia', '800');
INSERT INTO tableName (movie, released) VALUES ('Criaturas Celestiales', '801');
INSERT INTO tableName (movie, released) VALUES ('El Último Rey de Escocia', '802');
INSERT INTO tableName (movie, released) VALUES ('Interestelar', '803');
INSERT INTO tableName (movie, released) VALUES ('28 Días Después', '804');
INSERT INTO tableName (movie, released) VALUES ('Veer-Zaara', '805');
INSERT INTO tableName (movie, released) VALUES ('Atrapa a um Ladrón', '806');
INSERT INTO tableName (movie, released) VALUES ('La Fuerza del Cariño', '807');
INSERT INTO tableName (movie, released) VALUES ('Star Trek: Primer Contacto', '808');
INSERT INTO tableName (movie, released) VALUES ('Puedes Contar Conmigo', '809');
INSERT INTO tableName (movie, released) VALUES ('La Mala Educación', '810');
INSERT INTO tableName (movie, released) VALUES ('Mississippi en Llamas', '811');
INSERT INTO tableName (movie, released) VALUES ('Bestias del Sur Salvaje', '812');
INSERT INTO tableName (movie, released) VALUES ('Único Testigo', '813');
INSERT INTO tableName (movie, released) VALUES ('Pierrot, el Loco', '814');
INSERT INTO tableName (movie, released) VALUES ('El Hombre que Nunca Estuvo Allí', '815');
INSERT INTO tableName (movie, released) VALUES ('Suspense', '816');
INSERT INTO tableName (movie, released) VALUES ('Un Hombre para La Eternidad', '817');
INSERT INTO tableName (movie, released) VALUES ('El Libro Negro', '818');
INSERT INTO tableName (movie, released) VALUES ('Círculo Rojo', '819');
INSERT INTO tableName (movie, released) VALUES ('Half Nelson', '820');
INSERT INTO tableName (movie, released) VALUES ('Thelma & Louise', '821');
INSERT INTO tableName (movie, released) VALUES ('Walkabout', '822');
INSERT INTO tableName (movie, released) VALUES ('Cita em St. Louis', '823');
INSERT INTO tableName (movie, released) VALUES ('Monsieur Verdoux', '824');
INSERT INTO tableName (movie, released) VALUES ('Big', '825');
INSERT INTO tableName (movie, released) VALUES ('El Enigma de Gaspar House', '826');
INSERT INTO tableName (movie, released) VALUES ('El Sentido de La Vida', '827');
INSERT INTO tableName (movie, released) VALUES ('Billy Elliot', '828');
INSERT INTO tableName (movie, released) VALUES ('Los Puentes de Madison', '829');
INSERT INTO tableName (movie, released) VALUES ('Esse Oscuro Objeto del Deseo', '830');
INSERT INTO tableName (movie, released) VALUES ('De Ilusión También se Vive', '831');
INSERT INTO tableName (movie, released) VALUES ('Jackie Brown', '832');
INSERT INTO tableName (movie, released) VALUES ('La Caza del Octubre Rojo', '833');
INSERT INTO tableName (movie, released) VALUES ('Oliver Twist', '834');
INSERT INTO tableName (movie, released) VALUES ('Unidos', '835');
INSERT INTO tableName (movie, released) VALUES ('Isla de Perros', '836');
INSERT INTO tableName (movie, released) VALUES ('PK', '837');
INSERT INTO tableName (movie, released) VALUES ('La Última Noche', '838');
INSERT INTO tableName (movie, released) VALUES ('Camino a La Perdición', '839');
INSERT INTO tableName (movie, released) VALUES ('Zulú', '840');
INSERT INTO tableName (movie, released) VALUES ('Zombieland', '841');
INSERT INTO tableName (movie, released) VALUES ('Veredicto Final', '842');
INSERT INTO tableName (movie, released) VALUES ('Leviatán', '843');
INSERT INTO tableName (movie, released) VALUES ('La Caja de Pandora', '844');
INSERT INTO tableName (movie, released) VALUES ('Vengadores: End Game', '845');
INSERT INTO tableName (movie, released) VALUES ('Sin Tregua', '846');
INSERT INTO tableName (movie, released) VALUES ('Sympathy for Lady Vengeance', '847');
INSERT INTO tableName (movie, released) VALUES ('Dead Man', '848');
INSERT INTO tableName (movie, released) VALUES ('In the Loop', '849');
INSERT INTO tableName (movie, released) VALUES ('A Bittersweet Life', '850');
INSERT INTO tableName (movie, released) VALUES ('La Tormenta de Hielo', '851');
INSERT INTO tableName (movie, released) VALUES ('Brick', '852');
INSERT INTO tableName (movie, released) VALUES ('Um Plan Sencillo', '853');
INSERT INTO tableName (movie, released) VALUES ('Infierno de Cobardes', '854');
INSERT INTO tableName (movie, released) VALUES ('El Violinista en el Tejado', '855');
INSERT INTO tableName (movie, released) VALUES ('Los Falsificadores', '856');
INSERT INTO tableName (movie, released) VALUES ('The Cameraman', '857');
INSERT INTO tableName (movie, released) VALUES ('The Visitor', '858');
INSERT INTO tableName (movie, released) VALUES ('El Paciente Inglés', '859');
INSERT INTO tableName (movie, released) VALUES ('Los Cañones de Navarone', '860');
INSERT INTO tableName (movie, released) VALUES ('Hoosiers: Más que Ídolos', '861');
INSERT INTO tableName (movie, released) VALUES ('Depredador', '862');
INSERT INTO tableName (movie, released) VALUES ('Pi, Fe en el Caos', '863');
INSERT INTO tableName (movie, released) VALUES ('Una Habitación con Vistas', '864');
INSERT INTO tableName (movie, released) VALUES ('Chacal', '865');
INSERT INTO tableName (movie, released) VALUES ('Blue Valentine', '866');
INSERT INTO tableName (movie, released) VALUES ('Titanic', '867');
INSERT INTO tableName (movie, released) VALUES ('Náufrago', '868');
INSERT INTO tableName (movie, released) VALUES ('Gattaca', '869');
INSERT INTO tableName (movie, released) VALUES ('Fish Tank', '870');
INSERT INTO tableName (movie, released) VALUES ('Ray', '871');
INSERT INTO tableName (movie, released) VALUES ('No se lo Digas a Nadie', '872');
INSERT INTO tableName (movie, released) VALUES ('El Cuervo', '873');
INSERT INTO tableName (movie, released) VALUES ('Todos nos Llamamos Alí', '874');
INSERT INTO tableName (movie, released) VALUES ('Donde está el Policía?', '875');
INSERT INTO tableName (movie, released) VALUES ('Fuga de Alcatraz', '876');
INSERT INTO tableName (movie, released) VALUES ('Forajidos', '877');
INSERT INTO tableName (movie, released) VALUES ('Amor Eterno', '878');
INSERT INTO tableName (movie, released) VALUES ('Mejor... Imposible', '879');
INSERT INTO tableName (movie, released) VALUES ('La Propuesta', '880');
INSERT INTO tableName (movie, released) VALUES ('X-Men 2', '881');
INSERT INTO tableName (movie, released) VALUES ('La Tienda en la Calle Mayor', '882');
INSERT INTO tableName (movie, released) VALUES ('Napoleón', '883');
INSERT INTO tableName (movie, released) VALUES ('Fearless', '884');
INSERT INTO tableName (movie, released) VALUES ('Mi Villano Favorito', '885');
INSERT INTO tableName (movie, released) VALUES ('El Viento que Agita la Cebada', '886');
INSERT INTO tableName (movie, released) VALUES ('Campo de Sueños', '887');
INSERT INTO tableName (movie, released) VALUES ('El Aviador', '888');
INSERT INTO tableName (movie, released) VALUES ('Collateral', '889');
INSERT INTO tableName (movie, released) VALUES ('Una História Violenta', '890');
INSERT INTO tableName (movie, released) VALUES ('Sonata de Otoño', '891');
INSERT INTO tableName (movie, released) VALUES ('El Inquilino', '892');
INSERT INTO tableName (movie, released) VALUES ('Madame de...', '893');
INSERT INTO tableName (movie, released) VALUES ('El Hombre sin Pasado', '894');
INSERT INTO tableName (movie, released) VALUES ('Dos Días, Uma Noche', '895');
INSERT INTO tableName (movie, released) VALUES ('Harry Potter y El Cáliz de Fuego', '896');
INSERT INTO tableName (movie, released) VALUES ('Chicago', '897');
INSERT INTO tableName (movie, released) VALUES ('Acorralado', '898');
INSERT INTO tableName (movie, released) VALUES ('Un Romance Peligroso', '899');
INSERT INTO tableName (movie, released) VALUES ('Sin City', '900');
INSERT INTO tableName (movie, released) VALUES ('La Carreta Fantasma', '901');
INSERT INTO tableName (movie, released) VALUES ('Mulan', '902');
INSERT INTO tableName (movie, released) VALUES ('La Chica que Saltaba a Través del Tiempo', '903');
INSERT INTO tableName (movie, released) VALUES ('El Secreto de Vivir', '904');
INSERT INTO tableName (movie, released) VALUES ('Gracias por Fumar', '905');
INSERT INTO tableName (movie, released) VALUES ('El Silencio', '906');
INSERT INTO tableName (movie, released) VALUES ('Thor: Ragnarok', '907');
INSERT INTO tableName (movie, released) VALUES ('Tombstone', '908');
INSERT INTO tableName (movie, released) VALUES ('Videodrome', '909');
INSERT INTO tableName (movie, released) VALUES ('Un Asesino Algo Especial', '910');
INSERT INTO tableName (movie, released) VALUES ('La Última Tentación de Cristo', '911');
INSERT INTO tableName (movie, released) VALUES ('Alma en Suplicio', '912');
INSERT INTO tableName (movie, released) VALUES ('Bloody Sunday', '913');
INSERT INTO tableName (movie, released) VALUES ('Ghost Dog', '914');
INSERT INTO tableName (movie, released) VALUES ('El Cuchillo en el Água', '915');
INSERT INTO tableName (movie, released) VALUES ('La Clase', '916');
INSERT INTO tableName (movie, released) VALUES ('Sexo, Mentiras y Vídeo', '917');
INSERT INTO tableName (movie, released) VALUES ('El Origen del Planeta de los Simios', '918');
INSERT INTO tableName (movie, released) VALUES ('Hunter', '919');
INSERT INTO tableName (movie, released) VALUES ('Plan Oculto', '920');
INSERT INTO tableName (movie, released) VALUES ('Indiana Jones y el Templo Maldito', '921');
INSERT INTO tableName (movie, released) VALUES ('El Asesinato de Jesse James por el Cobarde Robert Ford', '922');
INSERT INTO tableName (movie, released) VALUES ('IP Man 2', '923');
INSERT INTO tableName (movie, released) VALUES ('Chugyeogja', '924');
INSERT INTO tableName (movie, released) VALUES ('Elizabeth', '925');
INSERT INTO tableName (movie, released) VALUES ('Swingers', '926');
INSERT INTO tableName (movie, released) VALUES ('Descubriendo Nunca Jamás', '927');
INSERT INTO tableName (movie, released) VALUES ('The Ring', '928');
INSERT INTO tableName (movie, released) VALUES ('Aparajito', '929');
INSERT INTO tableName (movie, released) VALUES ('Bullit', '930');
INSERT INTO tableName (movie, released) VALUES ('Bambi', '931');
INSERT INTO tableName (movie, released) VALUES ('Dejad Paso al Mañana', '932');
INSERT INTO tableName (movie, released) VALUES ('Follow the Fleet', '933');
INSERT INTO tableName (movie, released) VALUES ('Kes', '934');
INSERT INTO tableName (movie, released) VALUES ('Submarine', '935');
INSERT INTO tableName (movie, released) VALUES ('El Libro de la Selva', '936');
INSERT INTO tableName (movie, released) VALUES ('21 Gramos', '937');
INSERT INTO tableName (movie, released) VALUES ('Kung Fu Panda', '938');
INSERT INTO tableName (movie, released) VALUES ('Zatoichi', '939');
INSERT INTO tableName (movie, released) VALUES ('La Pícara Puritana', '940');
INSERT INTO tableName (movie, released) VALUES ('En La Habitación', '941');
INSERT INTO tableName (movie, released) VALUES ('Sonrisas de una Noche de Verano', '942');
INSERT INTO tableName (movie, released) VALUES ('Algo em Común', '943');
INSERT INTO tableName (movie, released) VALUES ('Borat', '944');
INSERT INTO tableName (movie, released) VALUES ('El Juego de las Lágrimas', '945');
INSERT INTO tableName (movie, released) VALUES ('Boy A', '946');
INSERT INTO tableName (movie, released) VALUES ('Dies Irae', '947');
INSERT INTO tableName (movie, released) VALUES ('El Cocinero, El Ladrón, Su Mujer y Su Amante', '948');
INSERT INTO tableName (movie, released) VALUES ('Speed', '949');
INSERT INTO tableName (movie, released) VALUES ('Burt Munro, Un Sueño, Una Leyenda', '950');
INSERT INTO tableName (movie, released) VALUES ('Escándalo', '951');
INSERT INTO tableName (movie, released) VALUES ('Iván El Terrible', '952');
INSERT INTO tableName (movie, released) VALUES ('Arma Letal', '953');
INSERT INTO tableName (movie, released) VALUES ('Código Fuente', '954');
INSERT INTO tableName (movie, released) VALUES ('El Rey Pescador', '955');
INSERT INTO tableName (movie, released) VALUES ('Tirad Sobre El Pianista', '956');
INSERT INTO tableName (movie, released) VALUES ('La Extraña Pasajera', '957');
INSERT INTO tableName (movie, released) VALUES ('127 Horas', '958');
INSERT INTO tableName (movie, released) VALUES ('El Eclipse', '959');
INSERT INTO tableName (movie, released) VALUES ('Toni Erdmann', '960');
INSERT INTO tableName (movie, released) VALUES ('La Ley de la Hospitalidad', '961');
INSERT INTO tableName (movie, released) VALUES ('Dark City', '962');
INSERT INTO tableName (movie, released) VALUES ('Philadelphia', '963');
INSERT INTO tableName (movie, released) VALUES ('Madre!', '964');
INSERT INTO tableName (movie, released) VALUES ('Tucker & Dale Contra El Mal', '965');
INSERT INTO tableName (movie, released) VALUES ('De Mendigo a Millonario', '966');
INSERT INTO tableName (movie, released) VALUES ('Gosford Park', '967');
INSERT INTO tableName (movie, released) VALUES ('Menace II Society', '968');
INSERT INTO tableName (movie, released) VALUES ('Precious', '969');
INSERT INTO tableName (movie, released) VALUES ('Tres Reyes', '970');
INSERT INTO tableName (movie, released) VALUES ('Spider-Man: Un Nuevo Universo', '971');
INSERT INTO tableName (movie, released) VALUES ('Pelham 1.2.3.', '972');
INSERT INTO tableName (movie, released) VALUES ('El Matrimonio de Maria Broun', '973');
INSERT INTO tableName (movie, released) VALUES ('Munich', '974');
INSERT INTO tableName (movie, released) VALUES ('Lejos del Cielo', '975');
INSERT INTO tableName (movie, released) VALUES ('El Nuevo Entrenador', '976');
INSERT INTO tableName (movie, released) VALUES ('El Desafio de las Águilas', '977');
INSERT INTO tableName (movie, released) VALUES ('Re-Animator', '978');
INSERT INTO tableName (movie, released) VALUES ('Gigante', '979');
INSERT INTO tableName (movie, released) VALUES ('De Óxido y Hueso', '980');
INSERT INTO tableName (movie, released) VALUES ('Mi Nombre es Khan', '981');
INSERT INTO tableName (movie, released) VALUES ('Algunos Hombres Buenos', '982');
INSERT INTO tableName (movie, released) VALUES ('Gilda', '983');
INSERT INTO tableName (movie, released) VALUES ('Pequeño Gran Hombre', '984');
INSERT INTO tableName (movie, released) VALUES ('Abyss', '985');
INSERT INTO tableName (movie, released) VALUES ('La Gran Estafa Americana', '986');
INSERT INTO tableName (movie, released) VALUES ('Aquí y Ahora', '987');
INSERT INTO tableName (movie, released) VALUES ('Moulin Rouge', '988');
INSERT INTO tableName (movie, released) VALUES ('Juegos Secretos', '989');
INSERT INTO tableName (movie, released) VALUES ('Ángeles com Caras Sucias', '990');
INSERT INTO tableName (movie, released) VALUES ('Black Hawk Down', '991');
INSERT INTO tableName (movie, released) VALUES ('La Reina', '992');
INSERT INTO tableName (movie, released) VALUES ('Dumbo', '993');
INSERT INTO tableName (movie, released) VALUES ('La Venganza de Manon', '994');
INSERT INTO tableName (movie, released) VALUES ('Carta de una Desconocida', '995');
INSERT INTO tableName (movie, released) VALUES ('Zombi. El Regreso de los Muertos Vivientes', '996');
INSERT INTO tableName (movie, released) VALUES ('Capitán de Mar y Guerra', '997');
INSERT INTO tableName (movie, released) VALUES ('Lone Star', '998');
INSERT INTO tableName (movie, released) VALUES ('Drugstore Cowboy', '999');
